receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317  # Mude de 127.0.0.1 para 0.0.0.0
      http:
        endpoint: 0.0.0.0:4318  # Mude de 127.0.0.1 para 0.0.0.0

processors:
  batch:

exporters:
  otlp:
    endpoint: jaeger:4317
    tls:
      insecure: true

  debug:
    verbosity: normal

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp, debug]
 